### PR TITLE
PERF: Store a temporary buffer in OakRReference to avoid looking for one for each request

### PR DESCRIPTION
**Pull request by liran-funaro**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by sanastas** [comment]
I am sorry, I do not see what exactly is the gain of this tmp addition. What are we saving? Only the access to ThreadIndexCalculator? When TIC is not built on Atomic it should be not so much.

This fix limits Oak abilities in general, and we can get to it only if we see big change in performance, let say above 15%. Let us apply all other changes then run again with and without temp buffer and see how much do we gain.

**Comment by liran-funaro** [comment]
Irrelevant at this point

**Comment by sanastas** [comment]
I am closing this PR, because new OakBuffer interface will soon be out, as discussed internally.

**Comment by sanastas** [comment]
OK. Liran just closed it :)

**Pull request closed without merging**
